questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/<int:pk>/', views.TestView.as_view(), name='tests'),
    path(
        'question/<int:question_id>/',
        views.question,
        name='question'
    ),
    path('question/<int:pk>/vote/', views.vote, name='vote'),
    path('results/<int:test_id>/', views.results, name='result')
]

testwork/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('questions.urls', namespace='questions')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

questions/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Test(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название теста'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'


class Question(models.Model):
    test_id = models.ForeignKey(
        Test,
        on_delete=models.CASCADE,
        related_name='questions'
    )
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.CharField(max_length=100)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Answer(models.Model):
    question_id = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='answers'
    )
    answer = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)
    correct = models.BooleanField()

    def __str__(self):
        return self.answer


class Result(models.Model):
    test_id = models.ForeignKey(
        Test,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    result_rating = models.FloatField()

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    """Класс CreationForm, определяет форму для регистрации."""
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

questions/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView

from .models import Answer, Result, Test, Question


@login_required
def index(request):
    template = 'questions/index.html'
    tests = Test.objects.all()
    context = {
        'tests': tests,
    }
    return render(request, template, context)


class TestView(DetailView):
    template_name = 'questions/test.html'
    context_object_name = 'test'

    def get_object(self):
        test_id = self.kwargs.get('pk')
        return Test.objects.get(pk=test_id)


def question(request, question_id):
    question = Question.objects.get(pk=question_id)
    test = question.test_id.questions.values_list('id')
    last_question_id = list(test)[-1][0]
    correct_answer = question.answers.filter(correct=True).count()
    template_name = 'questions/question.html'
    context = {
        "question": question,
        "correct_answer": correct_answer,
        "last_question_id": last_question_id
    }
    return render(request, template_name, context)


def vote(request, pk):
    q = Question.objects.get(id=pk)
    if request.method == 'POST':
        answers_id = request.POST.getlist('answer')
        count = 0
        for answer in answers_id:
            if Answer.objects.get(id=answer).correct:
                answer = Answer.objects.get(id=answer)
                count += 10
                answer.vote += 1
            else:
                answer = Answer.objects.get(id=answer)
                count -= 10
                answer.vote += 1
            Result.objects.update(
                id=29,
                result_rating=count,
                user=request.user,
                test_id=q.test_id
            )
            return redirect('questions:question', pk+1)
        print(count)
        return redirect('questions:result', q.test_id.id)


def results(request, test_id):
    result = Result.objects.filter(test_id=test_id)
    print(result)
    template = 'questions/results.html'
    context = {
        'results': result,
    }
    return render(request, template, context)

users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    """Класс SignUp - обработчик данных страницы регистрации.
    form_class - объект формы
    template_name - путь к шаблону
    success_url - переадресация в случае успеха."""
    form_class = CreationForm
    success_url = reverse_lazy('questions:index')
    template_name = 'users/signup.html'

templates/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<html lang="ru">
  <header>    
    {% include 'includes/header.html' %}
    <title>{% block title %}Страница с шаблонами{% endblock %}</title>
  </header>
  <body>
    <main>
      {% block content %}
      {% endblock %}
    </main>      
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}    
    </footer>
  </body>

templates/includes/footer.html
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © {% now "Y" %} Copyright: Ivan Alexeev
</div>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'questions:index' %}">Опросник</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'questions:index' %}"> Главная страница</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Результаты</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
          </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Зарегистрироваться</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

templates/questions/index.html
{% extends 'base.html' %}
{% load user_filters %}
{% block content %}
{% for test in tests %}
    <p>
    <div class="p-3 mb-2 bg-secondary text-white">
    <strong>{{ test }}</strong>
    </div>
    </p>
    <a type="button" href="{% url 'questions:tests' test.id %} " class="btn btn-secondary btn-sm">Перейти к тесту</a>
{% endfor %} 
{% endblock %}

templates/questions/question.html
{% extends 'base.html' %}
{% block content %}

    <div class="p-3 mb-2 bg-secondary text-white">
        <strong>{{ question.question }}</strong>
    </div>
        {% for answer in question.answers.all %}
        <form method="post"
        action="{% url 'questions:vote' question.id %}">
        {% if correct_answer == 1 %}
            <p>
                <h6>
                <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
                    <label for="answer{{ forloop.counter }}">{{ answer.answer }}</label>
                </h6>
            </p>
        {% else %} 
            <p>
                <h6>
                <input type="checkbox" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
                    <label for="answer{{ forloop.counter }}">{{ answer.answer }}</label>
                </h6>
            </p>
        {% endif %}
        {% endfor %}
        {% if question.id != last_question_id %}
        <button type="submit">Следующий вопрос</button>
        {% else %}
        <form>
        <button  type="submit">Сдать тест</button></a>
        {% endif %}
        {% csrf_token %}
        </form>
            <a type="button" href="{% url 'questions:tests' question.test_id.id %} " class="btn btn-secondary btn-sm">Назад к тесту "{{ question.test_id }}"</a>
    {% endblock %}

templates/questions/results.html
{% extends "base.html" %}
{% block content %}
{% for result in results %}
    {{ result.test_id }}
    <p>Результат: {{ result.result_rating }}</p>
    {% if result.result_rating < 10 %}
        ТЕСТ НЕ ПРОЙДЕН
    {% else %}
        ТЕСТ ПРОЙДЕН
    {% endif %}
{% endfor %}
{% endblock %}

templates/questions/test.html
{% extends 'base.html' %}
{% block content %}
    <div class="p-3 mb-2 bg-secondary text-white">
        <strong>{{ test }}</strong>
    </div>

    {% for questions in test.questions.all %}
        <p>{{ questions.question }}
        <a type="button" href="{% url 'questions:question' questions.id %}" class="btn btn-secondary btn-sm">Перейти к вопросу</a>
        </p>
    {% endfor %}
{% endblock %}

templates/users/logged_out.html
{% extends "base.html" %}

{% block content %}
Вы вышли
<a class="btn btn-outline-danger" href="{% url 'users:login' %}"> Войти заново</a>
{% endblock %}

templates/users/login.html
{% load static %}
{% load user_filters %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
                  <div class="text-center">
                    <h4 class="mt-1 mb-5 pb-1">Опросник</h4>
                  </div>
                    <p>Войдите в аккаунт:</p>
                          {% if form.errors %}
                            {% for field in form %}
                              {% for error in field.errors %}            
                                <div class="alert alert-danger">
                                  {{ error|escape }}
                                </div>
                              {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                              <div class="alert alert-danger">
                                {{ error|escape }}
                              </div>
                            {% endfor %}
                        {% endif %}

                        <form method="post"
                          {% if action_url %}
                            action="{% url action_url %}"
                          {% endif %}
                        >
                        {% csrf_token %}
                        {% for field in form %}
                          <div class="form-group row my-3"
                            {% if field.field.required %} 
                              aria-required="true"
                            {% else %}
                              aria-required="false"
                            {% endif %}
                          >
                            <label for="{{ field.id_for_label }}">
                              {{ field.label }}
                                {% if field.field.required %}
                                  <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            <div>
                            {{ field|addclass:'form-control' }}
                              {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                  {{ field.help_text|safe }}
                                </small>
                              {% endif %}
                            </div>
                          </div>
                        {% endfor %}
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Войти</button>
                      <a class="text-muted" href="#!">Забыли пароль?</a>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Нет аккаунта?</p>
                      <a class="btn btn-outline-danger" href="{% url 'users:signup' %}"> Зарегистрироваться</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/users/signup.html
{% load static  %}
{% load user_filters %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
                  <div class="text-center">
                    <h4 class="mt-1 mb-5 pb-1">Опросник</h4>
                  </div>
                    <p>Зарегистрируйтесь:</p>
                          {% if form.errors %}
                          {% for field in form %} 
                            {% for error in field.errors %}            
                              <div class="alert alert-danger">
                                {{ error|escape }}
                              </div>
                            {% endfor %}
                          {% endfor %}
                          {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                              {{ error|escape }}
                            </div>
                          {% endfor %}
                      {% endif %}
        
                      <form method="post" action="{% url 'users:signup' %}">
                      {% csrf_token %}
  
                      {% for field in form %} 
                        <div class="form-group row my-3">
                          <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                              {% if field.field.required %}
                                <span class="required text-danger">*</span>
                              {% endif %}
                          </label>
                          {{ field|addclass:'form-control' }} 
                            {% if field.help_text %}
                              <small 
                                id="{{ field.id_for_label }}-help"
                                class="form-text text-muted"
                              >
                                {{ field.help_text|safe }}
                              </small>
                            {% endif %}
                        </div>
                      {% endfor %}
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button type="submit" class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3">
                        Зарегистрироваться
                      </button>
                    </div>
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Уже есть аккаунт?</p>
                      <a class="btn btn-outline-danger" href="{% url 'users:login' %}"> Войти</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>